In [1]:
import pandas as pd
import numpy as np
import tensorflow
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
data = pd.read_csv('F:/Social Prachar/Raj sir/july/15 july 2021/train.csv')
data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
X = data.iloc[:,1:]
X.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
y = data.iloc[:,0]
y.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [5]:
model = Sequential()
model.add(Dense(256,input_dim=784,activation='sigmoid'))
model.add(Dense(132,activation='relu'))
model.add(Dense(64,activation='tanh'))

model.add(Dense(10,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [6]:
from keras.utils.all_utils import to_categorical

In [7]:
y = to_categorical(y)
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [8]:
model.fit(X,y,validation_split=0.2,epochs=30,verbose=2)

Epoch 1/30
1050/1050 - 2s - loss: 0.5022 - accuracy: 0.8465 - val_loss: 0.3844 - val_accuracy: 0.8804
Epoch 2/30
1050/1050 - 1s - loss: 0.3563 - accuracy: 0.8885 - val_loss: 0.3766 - val_accuracy: 0.8807
Epoch 3/30
1050/1050 - 2s - loss: 0.3143 - accuracy: 0.8998 - val_loss: 0.2990 - val_accuracy: 0.9054
Epoch 4/30
1050/1050 - 1s - loss: 0.2845 - accuracy: 0.9079 - val_loss: 0.2841 - val_accuracy: 0.9121
Epoch 5/30
1050/1050 - 1s - loss: 0.2693 - accuracy: 0.9133 - val_loss: 0.2766 - val_accuracy: 0.9102
Epoch 6/30
1050/1050 - 1s - loss: 0.2547 - accuracy: 0.9184 - val_loss: 0.2331 - val_accuracy: 0.9256
Epoch 7/30
1050/1050 - 1s - loss: 0.2543 - accuracy: 0.9187 - val_loss: 0.2668 - val_accuracy: 0.9146
Epoch 8/30
1050/1050 - 1s - loss: 0.2522 - accuracy: 0.9169 - val_loss: 0.2526 - val_accuracy: 0.9182
Epoch 9/30
1050/1050 - 1s - loss: 0.2272 - accuracy: 0.9264 - val_loss: 0.2218 - val_accuracy: 0.9287
Epoch 10/30
1050/1050 - 1s - loss: 0.2146 - accuracy: 0.9315 - val_loss: 0.2155 - val_accuracy: 0.9299
Epoch 11/30
1050/1050 - 1s - loss: 0.2261 - accuracy: 0.9261 - val_loss: 0.2207 - val_accuracy: 0.9288
Epoch 12/30
1050/1050 - 1s - loss: 0.2056 - accuracy: 0.9326 - val_loss: 0.2027 - val_accuracy: 0.9364
Epoch 13/30
1050/1050 - 1s - loss: 0.2056 - accuracy: 0.9331 - val_loss: 0.2023 - val_accuracy: 0.9379
Epoch 14/30
1050/1050 - 2s - loss: 0.1976 - accuracy: 0.9359 - val_loss: 0.1961 - val_accuracy: 0.9383
Epoch 15/30
1050/1050 - 1s - loss: 0.1924 - accuracy: 0.9388 - val_loss: 0.2272 - val_accuracy: 0.9256
Epoch 16/30
1050/1050 - 2s - loss: 0.1958 - accuracy: 0.9356 - val_loss: 0.1917 - val_accuracy: 0.9395
Epoch 17/30
1050/1050 - 1s - loss: 0.1857 - accuracy: 0.9408 - val_loss: 0.1990 - val_accuracy: 0.9374
Epoch 18/30
1050/1050 - 2s - loss: 0.1877 - accuracy: 0.9390 - val_loss: 0.1885 - val_accuracy: 0.9395
Epoch 19/30
1050/1050 - 1s - loss: 0.1882 - accuracy: 0.9391 - val_loss: 0.2035 - val_accuracy: 0.9373
Epoch 20/30
1050/1050 - 2s - loss: 0.1811 - accuracy: 0.9409 - val_loss: 0.2076 - val_accuracy: 0.9331
Epoch 21/30
1050/1050 - 1s - loss: 0.1731 - accuracy: 0.9454 - val_loss: 0.1732 - val_accuracy: 0.9440
Epoch 22/30
1050/1050 - 1s - loss: 0.1699 - accuracy: 0.9456 - val_loss: 0.1771 - val_accuracy: 0.9427
Epoch 23/30
1050/1050 - 1s - loss: 0.1673 - accuracy: 0.9474 - val_loss: 0.1818 - val_accuracy: 0.9430
Epoch 24/30
1050/1050 - 1s - loss: 0.1622 - accuracy: 0.9471 - val_loss: 0.1866 - val_accuracy: 0.9387
Epoch 25/30
1050/1050 - 1s - loss: 0.1588 - accuracy: 0.9487 - val_loss: 0.1857 - val_accuracy: 0.9419
Epoch 26/30
1050/1050 - 2s - loss: 0.1514 - accuracy: 0.9517 - val_loss: 0.1674 - val_accuracy: 0.9495
Epoch 27/30
1050/1050 - 2s - loss: 0.1523 - accuracy: 0.9512 - val_loss: 0.1731 - val_accuracy: 0.9450
Epoch 28/30
1050/1050 - 1s - loss: 0.1523 - accuracy: 0.9524 - val_loss: 0.1673 - val_accuracy: 0.9464
Epoch 29/30
1050/1050 - 1s - loss: 0.1506 - accuracy: 0.9523 - val_loss: 0.1716 - val_accuracy: 0.9460
Epoch 30/30
1050/1050 - 1s - loss: 0.1413 - accuracy: 0.9542 - val_loss: 0.1501 - val_accuracy: 0.9515

In [10]:
model.save('mnistt.h5')

In [12]:
model.predict_classes(X)[:10]

C:\Users\ganes\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '

array([1, 0, 1, 4, 0, 0, 7, 3, 5, 3], dtype=int64)

In [13]:
y[:10]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 256)               200960
_________________________________________________________________
dense_1 (Dense)              (None, 132)               33924
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8512
_________________________________________________________________
dense_3 (Dense)              (None, 10)                650
=================================================================
Total params: 244,046
Trainable params: 244,046
Non-trainable params: 0
_________________________________________________________________